name: Publish npm package on Git tag

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
