name: Publish nightly

on:
  schedule:
    - cron: "30 9 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Bump version and publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # commit for patch
        run: |
          npm version patch -m "Bump version to %s for nightly release"
          npm publish
